version: "3.9"

services:

  php:
    build:
      context: ./
    container_name: php
    hostname: php-container
    restart: unless-stopped
    volumes:
      - ./www:/var/www
    environment:
      TZ: "Europe/Moscow"
    networks:
      - default
    healthcheck:
      test: curl -s http://nginx | grep works
      interval: 20s
      timeout: 3s
      retries: 5

  nginx:
    image: nginx
    container_name: nginx
    hostname: nginx-container
    restart: unless-stopped
    volumes:
      - ./nginx/dev.conf:/etc/nginx/conf.d/default.conf
      - ./www:/var/www
    ports:
      - 80:80
    environment:
      TZ: "Europe/Moscow"
    networks:
      - default

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 192.168.251.0/25
